services:
  frankenphp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    command: ["frankenphp", "run", "--config", "/app/Caddyfile"]

  database:
    image: mariadb:latest
    container_name: symfony-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  memcached:
    image: memcached:alpine
    container_name: symfony-cache
    restart: unless-stopped
    ports:
      - "11211:11211"
volumes:
  db-data:
